# Generated by Django 6.0.6 on 2026-06-11 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Orphanage Manager'), ('social_worker', 'Social Worker'), ('nurse', 'Nurse'), ('caregiver', 'Caregiver'), ('driver', 'Driver'), ('security', 'Security'), ('kitchen', 'Kitchen Staff'), ('teacher', 'Teacher')], default='caregiver', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
