# Generated by Django 6.0.6 on 2026-06-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'System Administrator'), ('orphanage_director', 'Orphanage Director'), ('social_worker', 'Social Worker'), ('healthcare_worker', 'Healthcare Worker'), ('village_head', 'Village Head'), ('donor', 'Donor / Sponsor'), ('government_official', 'Government Official')], default='social_worker', max_length=30),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
