# Generated by Django 6.0.6 on 2026-06-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orphanage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('faith_based', 'Faith Based'), ('ngo', 'NGO')], default='public', max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('director_name', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('current_children', models.IntegerField(default=0)),
                ('staff_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
