# Generated by Django 6.0.6 on 2026-06-11 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('village', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_contact', models.CharField(blank=True, max_length=20)),
                ('reason_for_care', models.TextField()),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('ENROLLED', 'Enrolled'), ('TRANSFERRED', 'Transferred'), ('REUNITED', 'Reunited with Family')], default='PENDING', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='child_photos/')),
                ('reporter_role', models.CharField(blank=True, max_length=100)),
                ('medical_notes', models.TextField(blank=True)),
                ('special_needs', models.TextField(blank=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_children', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
