# Generated by Django 6.0.6 on 2026-06-12 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_medicalrecord_vaccination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination',
            name='child',
        ),
        migrations.AddField(
            model_name='child',
            name='emergency_type',
            field=models.CharField(blank=True, choices=[('birth_loss', 'Mother passed during childbirth'), ('abandoned', 'Abandoned newborn/infant'), ('medical_emergency', 'Critical medical condition'), ('abuse', 'Child abuse/neglect case')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='health_facility',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='needs_immediate_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='child',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='child',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('ENROLLED', 'Enrolled'), ('EMERGENCY', 'Emergency Placement'), ('TRANSFERRED', 'Transferred'), ('REUNITED', 'Reunited with Family')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_notes', to='children.child')),
            ],
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
        migrations.DeleteModel(
            name='Vaccination',
        ),
    ]
