# Generated by Django 6.0.6 on 2026-06-12 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_remove_vaccination_child_child_emergency_type_and_more'),
        ('orphanages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='current_orphanage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='orphanages.orphanage'),
        ),
        migrations.AlterField(
            model_name='child',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('ENROLLED', 'Enrolled'), ('MEDICAL_CHECK', 'Medical Check'), ('AWAITING_BED', 'Awaiting Bed'), ('PLACED', 'Placed'), ('IN_CARE', 'In Care'), ('TRANSFERRED', 'Transferred'), ('REUNITED', 'Reunited with Family'), ('EMERGENCY', 'Emergency'), ('DECEASED', 'Deceased')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='children.child')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('date_given', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('administered_by', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='children.child')),
            ],
        ),
    ]
