# Generated by Django 6.0.6 on 2026-06-14 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_child_current_orphanage_alter_child_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='child',
            name='criteria_met',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='child',
            name='documents',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='child',
            name='enrollment_status',
            field=models.CharField(choices=[('INITIATED', 'Initiated - Pending Screening'), ('SCREENING', 'Under Social Worker Screening'), ('VERIFIED', 'Verified - Pending Approval'), ('APPROVED', 'Approved - Ready for Placement'), ('ENROLLED', 'Enrolled - Placement in Progress'), ('PLACED', 'Placed - In Care'), ('REJECTED', 'Rejected - Does Not Meet Criteria'), ('PENDING_INFO', 'Pending More Information')], default='INITIATED', max_length=20),
        ),
        migrations.AddField(
            model_name='child',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='child',
            name='placement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='child',
            name='screened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screened_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='child',
            name='screening_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='child',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_enrollments', to=settings.AUTH_USER_MODEL),
        ),
    ]
