# Generated by Django 6.0.6 on 2026-06-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0005_add_enrollment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending Review'), ('EMERGENCY', 'Emergency'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ENROLLED', 'Enrolled'), ('PLACED', 'Placed'), ('TRANSFERRED', 'Transferred'), ('REUNITED', 'Reunited')], default='PENDING', max_length=20),
        ),
    ]
