# Generated by Django 6.0.6 on 2026-06-15 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0006_alter_child_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casenote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='casenote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='casenote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
