# Generated by Django 6.0.6 on 2026-06-14 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanages', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='orphanage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='orphanages.orphanage'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
