# Generated by Django 6.0.6 on 2026-06-12 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanages', '0001_initial'),
        ('resources', '0002_orphanage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_beds', models.IntegerField()),
                ('occupied_beds', models.IntegerField(default=0)),
                ('color_code', models.CharField(default='blue', max_length=20)),
                ('orphanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='orphanages.orphanage')),
            ],
        ),
    ]
